version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/app
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src:/app
    working_dir: /var/www
  db:
    platform: 'linux/arm64'
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
  # mail:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   ports:
  #     - "8025:8025"
  #   environment:
  #     MH_STORAGE: maildir
  #     MH_MAILDIR_PATH: /tmp
  #   volumes:
  #     - maildir:/tmp
volumes:
  mysql-volume:
  # maildir: {}
